# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-redirect-from
- jekyll-feed
- jemoji
- jekyll-seo-tag
- jekyll-paginate

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: pagenate/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: isislab # jekyll-seo-tag > Owners twitter username
author: isislab # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: isislab # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/isislab
    - https://www.facebook.com/nyupolyisislab
    - https://github.com/isislab

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "OSIRIS" # Site name or title, also used in jekyll-seo-tag
logo: "https://osiris.cyber.nyu.edu/wp-content/uploads/2015/11/OSIRIS_LOGO_HORIZONTAL_MIXED.png" # Site logo, also used in jekyll-seo-tag
logoLink: /

# 8. Site navigation
  # When these links change, also change line 9 in _includes/nav-header.html
navigation_header:
  Getting Involved: /gettinginvolved/
  Industry: /industry/
  Members: /members/
  Research: /research/
  Newsletter: /newsletter/

navigation_footer:
  Sign Up: /newsletter/
  Contact: /contact/
  HackNight: http://hn.csaw.io/
  CSAW: https://csaw.engineering.nyu.edu/

social_links:
  Facebook: https://www.facebook.com/nyupolyisislab
  GitHub: https://github.com/isislab
  Twitter: https://twitter.com/isislab

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
  Email: ""
